from extractor.text_extractors import (
    JinnewsExtractor,
    NuhevExtractor,
    XwebunExtractor,
    LotikxaneExtractor,
    RojevaKurdExtractor,
    AjansawelatExtractor,
    BianetExtractor,
    AnfKurmanciExtractor,
    MezopotamyaExtractor,
    DengeEmerikaExtractor,
    RupelanuExtractor,
    SemakurdExtractor,
    CandnameExtractor,
    RojnewsExtractor,
    XebatExtractor,
    DiyarnameExtractor,
    PortalNeteweExtractor,
    KurdYekitiExtractor,
    KurdistanMediaExtractor,
)


DOMAIN_TO_EXTRACTOR = {
    "xwebun2.org": XwebunExtractor,
    "kurmanci.anf-news.com": AnfKurmanciExtractor,
    "nuhev.com": NuhevExtractor,
    "jinnews.net": JinnewsExtractor,
    "lotikxane.com": LotikxaneExtractor,
    "rojevakurd.com": RojevaKurdExtractor,
    "ajansawelat.com": AjansawelatExtractor,
    "bianet.org": BianetExtractor,
    "mezopotamyaajansi.com": MezopotamyaExtractor,
    "dengeamerika.com": DengeEmerikaExtractor,
    "rupelanu.com": RupelanuExtractor,
    "semakurd.net": SemakurdExtractor,
    "candname.com": CandnameExtractor,
    "rojnews.news": RojnewsExtractor,
    "xebat.net": XebatExtractor,
    "diyarname.com": DiyarnameExtractor,
    "portal.netewe.com": PortalNeteweExtractor,
    "kurdi.yekiti-media.org": KurdYekitiExtractor,
    "kurdistanmedia.com": KurdistanMediaExtractor,
}
